title: தி லீ ப் # name of the site
author: திலீப் கோனா # name of site's author
email: dilipgona@gmail.com # email of site's author
url: https://rosinantie.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: "Life.exe = [💻 24/7] + [🏋️ 4x] + [🏸 2x] + [🏃 1x] + [2AM]"
permalink: /:slug.html

favicon: "icons8-disco-ball-96.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true
  lab:
    output: true
